### ISSUE TITLE
Recommendations for tuning AsyncMultiTokenSink?

### ISSUE THREAD

**Issue by adampetrovic** [signalfx/golib#190]
Hi There!

We've recently added functionality to our metrics pipeline that allows us to send datapoints using an ingestion token based off a certain dimension value on our metrics. Previously we sent all datapoints using a single ingestion token using the `HTTPSink.AddDatapoints` method. With this change, we have migrated to using the `AsyncMultiTokenSink.AddDatapointsWithToken` method. With this method, when a batch of metrics comes in, we split the datapoints by their intended token and for any metrics that don't have their own token, we fall back to the same default token as in our old approach. For a given 'flush', we see about 60,000 datapoints per second  hitting the default token and about 3000 datapoints per second for individual service tokens (these numbers are for a single instance across ~30 c5.xlarge EC2 instances).

In switching to the new approach, we have noticed a fairly significant change in terms of the memory pressure / heap allocations. I suspect this is in part due to how the AsyncMultiTokenSink buffers metrics before sending onto the SignalFx ingestion endpoint (the HTTPSink.AddDatapoints method has no buffering).

Given the number of tuning options the AsyncMultiTokenSink provides, i'm afraid we haven't optimised these parameters to suit our workload / shape of data and was looking for some guidance from those that have experience running this sink type in production.

In particular, given the numbers above, we are handling about 90M DPM across currently running with the following settings in production:
```
NumChannels=1 
// we only choose a single channel, because selecting multiple channels when 90%~ of our metrics go to the default token would mean we'd have a 'hot channel' and the other channels would be heavily under-utilised. We instead scale by adding more workers

NumWorkers=1000
// my understanding of this parameter is the larger this number is, the more simultaneous requests to the SignalFx ingestion API we'll have

BufferSize=1000
// we only buffer if our workers aren't able to keep up with the workload. We haven't really seen this in production

BatchSize=10000
// the max number of datapoints we'll send in a single request to SignalFx
```

I'm wondering if anyone has recommendations / a formula for these parameters given a theoretic workload. For instance:

* What is the optimal BatchSize we should use / can SignalFx handle?
* Given an incoming number of datapoints per second / request and an instance size (e.g 4 CPUs / 8GB RAM) what should uor target number of channels / workers be?

Running a heap pprof shows that the bulk of our objects in use is the translation step we run to convert our statsd metrics to the SignalFx Datapoint format, which to me indicates something about the new Sink holding onto that memory and not freeing it as quickly as we used to, though the pprof shows no indication that it's a leak within the AsyncMultiTokenSink code. What's interesting is that the memory utilisation does not drop when we stop sending requests to the service and our CPU profile is approximately the same between the old and new approach.

Given we also see a drop from around 10~ GC operations per second to <1 per second, my gut feel here is that we're not seeing the GC being triggered enough (because our allocation hits a high enough peak early on to never see the heap double in size, which is the default behaviour of GOGC). I will be investigating whether making the GOGC value more aggressive helps alleviate the memory pressure.

I've attached the change in memory profile:

![GC Operations Per Second](https://i.imgur.com/z6KQS1j.png)
![Memory Utilisation](https://i.imgur.com/oo4S2XZ.png)

Any guidance would be greatly appreciated!

**Comment by adampetrovic** [comment]
After some testing over the past couple of days, I suspect i've found a memory leak in the emit logic.

https://github.com/signalfx/golib/blob/master/sfxclient/multitokensink.go#L207

The last step after we emit our datapoints is to assign the Datapoint worker buffer to the zero slice of the buffer we just sent. This resets our buffer but doesn't make the memory associated with the backing array available for garbage collection.

I will do some testing in staging on a fork of the worker to confirm this reduces the pressure on the heap.

I suspect the fix will be to set this buffer to nil (`w.buffer = nil`) which will mark the underlying array available for cleanup.

**Comment by adampetrovic** [comment]
CC @mdubbyap

**Comment by mdubbyap** [comment]
Internally we've actually gone away from using the MultiTokenSink to using a similar (but different) method in the BufferedForwarder setting useAuthFromRequest.  Could you take a look and see if this meets your needs?

As for the setting slice size to 0 (while keeping the capacity), yeah, i could understand how you might not want this under all circumstances, e.g. if that slice capacity is set to something really large. In our experiences it hasn't been a problem, but as i've said, we've moved away from this code internally.

Optimal batch size is probably pretty large. We won't accept more than a million in a single request. 30k, 100k? These are fine as long as you're timeouts are appropriate for the transmission of the data.

I'm going to sue the parlance of BufferedForwarder here, but NumDrainingThreads is roughly equivalent to num workers. The default is same as the num cores. This is fine in the case of not setting the useAuthFromRequest setting, but i would make it far higher as the batch sizes become much smaller in this case so you spend a lot more time waiting on network io.  We usually set this to 2xnum cores but i bet some finer tuning could produce better results depending on workload and # of tokens used.

**Comment by adampetrovic** [comment]
Appreciate the suggestion. In us tuning down the batch size to a reasonble amount we've seen memory usage start to drop quite a bit. I'll take it as an action to have a look at the BufferedForwarder when I get the chance.
