### ISSUE TITLE
github.com/signalfx/gohistogram repo gone?

### ISSUE THREAD

**Issue by powersj** [signalfx/golib#241]
Hi,

While the dependency for `github.com/signalfx/gohistogram` can still be collected, the repo itself is now gone it appears. Was this done on purpose? Is this dependency going to be changed? dropped?

I ask since as a part of the [telegraf](https://github.com/influxdata/telegraf) project we ensure we can get to all our dependencies and [validate their licences](https://github.com/influxdata/telegraf/issues/12344).

**Comment by powersj** [comment]
@breedx-splk thanks for the quick response!

It looks good now: https://app.circleci.com/pipelines/github/influxdata/telegraf/14136/workflows/0ac9ddf5-02c2-41cd-a211-f2d7a9588bd4/jobs/224827

Are you planning to remove the dependency or use the upstream?

**Comment by breedx-splk** [comment]
> Are you planning to remove the dependency or use the upstream?

@powersj Unfortunately I don't have a great answer. But we really should do _something_ because an outdated fork of a fork is a liability IMO.

**Comment by powersj** [comment]
ok, thanks for the follow-up. I am happy to close and again appreciate the quick response.
